### ISSUE TITLE
Outer weights

### ISSUE THREAD

**Issue by DhineshRET** [GoogleCloudPlatform/plspm-python#2]
Hi 

We used smartPLS before. We tried using your package. we have lots of difference in outer weights. we tried every scheme to match with our smartPLS output but nothing matches.

**Comment by jezhumble** [comment]
Hi Dhinesh. We calculate based on the same algorithm as the R package [plspm](https://github.com/gastonstat/plspm).

I am not surprised you get different results with smartPLS, it uses a different implementation. Unfortunately because it is closed source software there is no way for us to know how it calculates the results and to see where the difference lies.

All I can suggest is talking to somebody who knows more about the difference between the R implementation of plspm and smartPLS to try and understand the difference.

If you notice a difference between the R implementation and us, feel free to re-open a bug, providing the data set you are using, the complete parameters you are passing in to the R algorithm, and the output.
