### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by holder-fo** [GoogleCloudPlatform/plspm-python#5]
When I try to calculate the moderating effects from my data ("scores" from result of first sem, idea from the R plspm), it occurs to me that "division by zero" from "inner_summary.mean_communality", since all the "num_mvs_in_lv"==1. Any thing i doing wrong? Or i can't calculate moderating effect from this for now?

**Comment by jezhumble** [comment]
Please can you reply with your python code and the output from running it?

**Comment by holder-fo** [comment]
Thanks for your instant reply! 
I'm new to Python and know none about R, but for my research, i read the doc of _R plspm_ about how to do the pls-sem model.
Now i try to make clear my experience, FOLLOWING are things went wrong:
I fisrt calculate the product from output scores of "AQI" and "OC" from my FIRST MODEL then use it as moderating model (SECOND MODEL) input data [mod_data.txt](https://github.com/GoogleCloudPlatform/plspm-python/files/4931755/mod_data.txt).

After that i run the model again with path matrix:

  | AQI | Ss | OC | AQI_mod_OC | Arr | AG0 | AG18 | AG41 | AG65
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0
1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0
1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0
1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0
1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0

then i encounter "division by zero" from "inner_summary.mean_communality".

I am not sure i make it clear, so demand any more materials or explanation if you need. 
Many thanks for your help!

**Comment by jezhumble** [comment]
Please post your python code and the output from running it, as I can't debug this problem without that.

**Comment by holder-fo** [comment]
Sorry for the misunderstanding! 
Now i upload my code and rawdata, hope it works! 
Since github not allows upload **csv** so i just change the file type name from **.cvs** and **.py** to **.txt**, you can change it back for running the code.
[raw_data.txt](https://github.com/GoogleCloudPlatform/plspm-python/files/4935254/raw_data.txt)
[sem-try.txt](https://github.com/GoogleCloudPlatform/plspm-python/files/4935273/sem-try.txt)

Thanks for your patience.

**Comment by jezhumble** [comment]
Thanks for providing your code and raw data. It works on my machine.

Are you sure you are using an up-to-date version of the plspm-python library? The latest version is 0.5.3. A bug similar to the one you are describing was present in an older version.

You can upgrade by running `pip install plspm --upgrade` (you may have to run `pip3 install plspm --upgrade` or `sudo pip3 install plspm --upgrade`).

If you've upgraded to the latest version and are still facing problems let me know.

**Comment by holder-fo** [comment]
Hi, Jez. I am quite sure i am using the latest version (i did upgrade the lib from 0.4.6 to 0.5.3)! I would reinstall it again and tell you the new condition.
BTW, i bumped into a new problem the other day, i am not sure that should i create a new issue or continue ask for help in this one.
Since it occurs with my same data and model uploaded, so i describe here:
when my moderating model (ie, the function "pls_sem_mod_whole" in my code) default setting the config, ie, default_scale=None, the code runs into endless loop. After debugging, i find it dies into calculating the variable "w_sign". Then i have no idea what to do due to my shallow knowledge. Hope you can help me find out why!
Thanks for your patience again!

**Comment by jezhumble** [comment]
I've released 0.5.4 which fixes the problem with divide by zero. The problem is that calculating goodness of fit is only possible if at least one latent variable has more than one item. Now the library will successfully generate an inner summary in all cases, but trying to retrieve goodness of fit will throw an exception.

For the second problem you report, this is caused by using MVs with the same names as LVs. This causes problems when the code tries to create a correlation matrix. I have added a check which prevents you from using MVs with the same names as LVs, which means you will need to change your code.

Please upgrade to 0.5.4 and let me know if this fixes the problem. If I don't hear from you in 1 week I'll assume this is fixed and close the bug.

One more thing - you have turned on bootstrap calculation but don't appear to be using the results. Please note that bootstrap calculations are computationally very expensive and your code will run many times quicker with them turned off.

Thank you for your bug report! If you find any further bugs, please open new bugs for them, even if the data / code are the same.

**Comment by holder-fo** [comment]
Thanks for your remind of bootstrap calculation, i need it in the future research that i didn't mention before. Again, thanks for your patience and bug fixes, now all works fine!

**Comment by jezhumble** [comment]
Great! Thanks again for reporting!
